name: Build and run tests
on: [push, pull_request]
env:
  app_id: pvr.mythtv

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: "Debian package test"
          os: ubuntu-latest
          CC: gcc
          CXX: g++
    steps:
    - name: Checkout Kodi repo
      uses: actions/checkout@v4
      with:
        repository: xbmc/xbmc
        ref: master
        path: xbmc
    - name: Checkout add-on repo
      uses: actions/checkout@v4
      with:
        path: ${{ env.app_id }}
    - name: Configure
      env:
        CC: ${{ matrix.CC }}
        CXX: ${{ matrix.CXX }}
      run: |
        cd ${app_id} && mkdir -p build && cd build
        cmake -DADDONS_TO_BUILD=${app_id} -DADDON_SRC_PREFIX=${{ github.workspace }} -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/xbmc/addons -DPACKAGE_ZIP=1 ${{ github.workspace }}/xbmc/cmake/addons
    - name: Build
      env:
        CC: ${{ matrix.CC }}
        CXX: ${{ matrix.CXX }}
      run: |
        cd ${app_id}/build
        make
